import datetime
from dateutil.relativedelta import relativedelta
import pandas as pd
import os
from faker import Faker

# import numpy as np

identification_type = [
    {
        "id": 1,
        "name": "cédula de  ciudadanía",
        "description": "ID for adults",
        "created_at": datetime.datetime.now(),
    },
    {
        "id": 2,
        "name": "tarjeta de identidad",
        "description": "ID for underage",
        "created_at": datetime.datetime.now(),
    },
    {
        "id": 3,
        "name": "NIT",
        "description": "ID for companies",
        "created_at": datetime.datetime.now(),
    },
    {
        "id": 4,
        "name": "Cédula de extranjería",
        "description": "ID for foreigners",
        "created_at": datetime.datetime.now(),
    },
]

status = [
    {
        "id": 1,
        "name": "active",
        "description": "user is currently active in platform",
        "created_at": datetime.datetime.now(),
    },
    {
        "id": 2,
        "name": "inactive",
        "description": "user is currently inactive in platform",
        "created_at": datetime.datetime.now(),
    },
    {
        "id": 3,
        "name": "blocked",
        "description": "user has been blocked",
        "created_at": datetime.datetime.now(),
    },
]

confirmation = [
    {
        "id": 1,
        "name": "false",
        "description": "Account created by another user, identity not confirmed.",
        "created_at": datetime.datetime.now(),
    },
    {
        "id": 2,
        "name": "email",
        "description": "Account confirmed through email.",
        "created_at": datetime.datetime.now(),
    },
    {
        "id": 3,
        "name": "ID",
        "description": "User and pet identity verified through ID document.",
        "created_at": datetime.datetime.now(),
    },
]

size = [
    {"size": "XS"},
    {"size": "S"},
    {"size": "M"},
    {"size": "L"},
    {"size": "XL"},
]

avatar = [
    {"name": "robot", "url": "http://robot_avatar.com"},
    {"name": "dog", "url": "http://dog_avatar.com"},
    {"name": "wolf", "url": "http://wolf_avatar.com"},
]

sex = [
    {"sex": "macho"},
    {"sex": "hembra"},
]

gender = [
    {"gender": "hombre"},
    {"gender": "mujer"},
    {"gender": "no binario"},
    {"gender": "otro"},
]


hobby = [
    {"name": "Walking", "icon": ""},
    {"name": "Playing Fetch", "icon": ""},
    {"name": "Swimming", "icon": ""},
    {"name": "Training", "icon": ""},
    {"name": "Interactive Toys", "icon": ""},
    {"name": "Hide and Seek", "icon": ""},
    {"name": "Chewing", "icon": ""},
    {"name": "Climbing", "icon": ""},
    {"name": "Scratching", "icon": ""},
    {"name": "Socializing", "icon": ""},
    {"name": "Grooming", "icon": ""},
    {"name": "Outdoor Exploration", "icon": ""},
    {"name": "Nature Walks", "icon": ""},
    {"name": "Agility Courses", "icon": ""},
    {"name": "Walking in the Park", "icon": ""},
    {"name": "Walking in the Mall", "icon": ""},
    {"name": "Interacting with Other Dogs", "icon": ""},
    {"name": "Interacting with Other Animals", "icon": ""},
    {"name": "Herding", "icon": ""},
    {"name": "Barking", "icon": ""},
    {"name": "Howling", "icon": ""},
    {"name": "Eating", "icon": ""},
    {"name": "Belly Rubs", "icon": ""},
    {"name": "Frisbee", "icon": ""},
]

parquet_dir = f"{os.getcwd()}/parquet"

coat = [
    {
        "name": "Black and White",
        "description": "Classic Border Collie coat color combination of black and white.",
        "url": "https://example.com/black_and_white_coat.jpg",
    },
    {
        "name": "Tri-color",
        "description": "Border Collie coat featuring black, white, and tan markings.",
        "url": "https://example.com/tri_color_coat.jpg",
    },
    {
        "name": "Blue Merle",
        "description": "Blue Merle Border Collie coat with mottled gray and black patterns.",
        "url": "https://example.com/blue_merle_coat.jpg",
    },
    {
        "name": "Red Merle",
        "description": "Red Merle Border Collie coat with mottled red and white patterns.",
        "url": "https://example.com/red_merle_coat.jpg",
    },
    {
        "name": "Sable",
        "description": "Border Collie coat with a base of brown or tan with black-tipped hairs.",
        "url": "https://example.com/sable_coat.jpg",
    },
    {
        "name": "Red and White",
        "description": "Border Collie coat color combination of red and white.",
        "url": "https://example.com/red_and_white_coat.jpg",
    },
    {
        "name": "Chocolate",
        "description": "Chocolate-colored Border Collie coat with deep brown coloration.",
        "url": "https://example.com/chocolate_coat.jpg",
    },
    {
        "name": "Lilac",
        "description": "Lilac-colored Border Collie coat with light brownish-gray coloration.",
        "url": "https://example.com/lilac_coat.jpg",
    },
    {
        "name": "Brindle",
        "description": "Border Collie coat with tiger-stripe-like markings in various shades.",
        "url": "https://example.com/brindle_coat.jpg",
    },
    {
        "name": "Parti-color",
        "description": "Parti-color Border Collie coat featuring large patches of two or more colors.",
        "url": "https://example.com/parti_color_coat.jpg",
    },
    {
        "name": "Tricolor Merle",
        "description": "A combination of black, white, and tan markings with a merle pattern overlay.",
        "url": "https://example.com/tricolor_merle_coat.jpg",
    },
    {
        "name": "Red and Tan",
        "description": "Red Border Collie coat with tan or cream markings.",
        "url": "https://example.com/red_and_tan_coat.jpg",
    },
    {
        "name": "Blue and Tan",
        "description": "Blue Border Collie coat with tan or cream markings.",
        "url": "https://example.com/blue_and_tan_coat.jpg",
    },
    {
        "name": "Saddleback",
        "description": "Border Collie coat pattern with darker coloration on the back resembling a saddle.",
        "url": "https://example.com/saddleback_coat.jpg",
    },
    {
        "name": "Masked",
        "description": "Border Collie coat pattern where the dog's face is darker than the rest of its body.",
        "url": "https://example.com/masked_coat.jpg",
    },
]

owner = [
    {
        "user_name": "owner1",
        "email": "owner1@example.com",
        "phone": "3504515971",
        "picture": "http://profile_pic.com",
        "avatar": 1,
        "password_hash": "hash1",
        "password_salt": "salt1",
        "status_id": 1,
        "confirmation_id": 1,
        "first_name": "John",
        "surname": "Doe",
        "second_surname": "Smith",
        "nickname": "JD",
        "identification_type_id": 1,
        "identification": "123456789",
        "address": "cra 43B # 82 - 204",
        "birthday": "1990-01-01",
        "birthplace": 20574,
        "gender": 1,
        "shirt_size_id": 1,
        "hat_size_id": 1,
        "pants_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "user_name": "owner2",
        "email": "owner2@example.com",
        "phone": "3504515972",
        "picture": "http://profile_pic.com",
        "avatar": 1,
        "password_hash": "hash2",
        "password_salt": "salt2",
        "status_id": 1,
        "confirmation_id": 1,
        "first_name": "Alice",
        "surname": "Johnson",
        "second_surname": "",
        "nickname": "AJ",
        "identification_type_id": 1,
        "identification": "987654321",
        "address": "cra 43B # 82 - 204",
        "birthday": "1985-03-15",
        "birthplace": 20574,
        "gender": 2,
        "shirt_size_id": 1,
        "hat_size_id": 1,
        "pants_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "user_name": "owner3",
        "email": "owner3@example.com",
        "phone": "3504515973",
        "picture": "http://profile_pic.com",
        "avatar": 1,
        "password_hash": "hash3",
        "password_salt": "salt3",
        "status_id": 1,
        "confirmation_id": 1,
        "first_name": "Michael",
        "surname": "Williams",
        "second_surname": "",
        "nickname": "Mikey",
        "identification_type_id": 1,
        "identification": "543216789",
        "address": "cra 43B # 82 - 204",
        "birthday": "1995-07-20",
        "birthplace": 20574,
        "gender": 1,
        "shirt_size_id": 1,
        "hat_size_id": 1,
        "pants_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "user_name": "owner4",
        "email": "owner4@example.com",
        "phone": "3504515974",
        "picture": "http://profile_pic.com",
        "avatar": 1,
        "password_hash": "hash4",
        "password_salt": "salt4",
        "status_id": 1,
        "confirmation_id": 1,
        "first_name": "Emily",
        "surname": "Brown",
        "second_surname": "",
        "nickname": "Em",
        "identification_type_id": 1,
        "identification": "987555321",
        "address": "cra 43B # 82 - 204",
        "birthday": "1988-12-10",
        "birthplace": 20574,
        "gender": 2,
        "shirt_size_id": 1,
        "hat_size_id": 1,
        "pants_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "user_name": "owner5",
        "email": "owner5@example.com",
        "phone": "3504515975",
        "picture": "http://profile_pic.com",
        "avatar": 1,
        "password_hash": "hash5",
        "password_salt": "salt5",
        "status_id": 1,
        "confirmation_id": 1,
        "first_name": "David",
        "surname": "Garcia",
        "second_surname": "",
        "nickname": "Dave",
        "identification_type_id": 1,
        "identification": "654441987",
        "address": "cra 43B # 82 - 204",
        "birthday": "1992-05-25",
        "birthplace": 20574,
        "gender": 1,
        "shirt_size_id": 1,
        "hat_size_id": 1,
        "pants_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "user_name": "owner6",
        "email": "owner6@example.com",
        "phone": "3504515976",
        "picture": "http://profile_pic.com",
        "avatar": 1,
        "password_hash": "hash6",
        "password_salt": "salt6",
        "status_id": 1,
        "confirmation_id": 1,
        "first_name": "Emma",
        "surname": "Martinez",
        "second_surname": "",
        "nickname": "Emmie",
        "identification_type_id": 1,
        "identification": "987124454",
        "address": "cra 43B # 82 - 204",
        "birthday": "1983-09-05",
        "birthplace": 20574,
        "gender": 2,
        "shirt_size_id": 1,
        "hat_size_id": 1,
        "pants_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "user_name": "owner7",
        "email": "owner7@example.com",
        "phone": "3504515977",
        "picture": "http://profile_pic.com",
        "avatar": 1,
        "password_hash": "hash7",
        "password_salt": "salt7",
        "status_id": 1,
        "confirmation_id": 1,
        "first_name": "Daniel",
        "surname": "Martinez",
        "second_surname": "",
        "nickname": "Danny",
        "identification_type_id": 1,
        "identification": "124446789",
        "address": "cra 43B # 82 - 204",
        "birthday": "1978-11-30",
        "birthplace": 20574,
        "gender": 1,
        "shirt_size_id": 1,
        "hat_size_id": 1,
        "pants_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "user_name": "owner8",
        "email": "owner8@example.com",
        "phone": "3504515978",
        "picture": "http://profile_pic.com",
        "avatar": 1,
        "password_hash": "hash8",
        "password_salt": "salt8",
        "status_id": 1,
        "confirmation_id": 1,
        "first_name": "Olivia",
        "surname": "Rodriguez",
        "second_surname": "",
        "nickname": "Liv",
        "identification_type_id": 1,
        "identification": "982224321",
        "address": "cra 43B # 82 - 204",
        "birthday": "1991-04-12",
        "birthplace": 20574,
        "gender": 2,
        "shirt_size_id": 1,
        "hat_size_id": 1,
        "pants_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
]

# Dogs
dog = [
    {
        "first_name": "Buddy",
        "middle_name": "",
        "surname": "Doe",
        "second_surname": "Smith",
        "nickname": "Buddy",
        "height": 30.5,
        "weight": 15.0,
        "sterilized": False,
        "description": "Friendly and playful",
        "birthday": "2018-05-15",
        "birthplace": 20574,
        "sex": 1,
        "coat": 1,
        "bandana_size_id": 1,
        "shirt_size_id": 1,
        "shoe_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "first_name": "Max",
        "middle_name": "",
        "surname": "Johnson",
        "second_surname": "",
        "nickname": "Max",
        "height": 40.0,
        "weight": 20.0,
        "sterilized": False,
        "description": "Loyal and energetic",
        "birthday": "2017-08-20",
        "birthplace": 20574,
        "sex": 1,
        "coat": 1,
        "bandana_size_id": 1,
        "shirt_size_id": 1,
        "shoe_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "first_name": "Luna",
        "middle_name": "",
        "surname": "Williams",
        "second_surname": "",
        "nickname": "Luna",
        "height": 35.0,
        "weight": 18.0,
        "sterilized": True,
        "description": "Affectionate and intelligent",
        "birthday": "2019-02-10",
        "birthplace": 20574,
        "sex": 2,
        "coat": 1,
        "bandana_size_id": 1,
        "shirt_size_id": 1,
        "shoe_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "first_name": "Charlie",
        "middle_name": "",
        "surname": "Brown",
        "second_surname": "",
        "nickname": "Charlie",
        "height": 45.0,
        "weight": 25.0,
        "sterilized": False,
        "description": "Energetic and intelligent",
        "birthday": "2016-11-25",
        "birthplace": 20574,
        "sex": 1,
        "coat": 1,
        "bandana_size_id": 1,
        "shirt_size_id": 1,
        "shoe_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "first_name": "Lucy",
        "middle_name": "",
        "surname": "Garcia",
        "second_surname": "",
        "nickname": "Lucy",
        "height": 32.0,
        "weight": 17.0,
        "sterilized": True,
        "description": "Playful and affectionate",
        "birthday": "2020-04-05",
        "birthplace": 20574,
        "sex": 2,
        "coat": 1,
        "bandana_size_id": 1,
        "shirt_size_id": 1,
        "shoe_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "first_name": "Cooper",
        "middle_name": "",
        "surname": "Martinez",
        "second_surname": "",
        "nickname": "Coop",
        "height": 38.0,
        "weight": 21.0,
        "sterilized": False,
        "description": "Friendly and obedient",
        "birthday": "2018-09-15",
        "birthplace": 20574,
        "sex": 1,
        "coat": 1,
        "bandana_size_id": 1,
        "shirt_size_id": 1,
        "shoe_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "first_name": "Molly",
        "middle_name": "",
        "surname": "Martinez",
        "second_surname": "",
        "nickname": "Molly",
        "height": 42.0,
        "weight": 23.0,
        "sterilized": True,
        "description": "Playful and intelligent",
        "birthday": "2017-06-30",
        "birthplace": 20574,
        "sex": 2,
        "coat": 1,
        "bandana_size_id": 1,
        "shirt_size_id": 1,
        "shoe_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "first_name": "Bailey",
        "middle_name": "",
        "surname": "Rodriguez",
        "second_surname": "",
        "nickname": "Bails",
        "height": 37.0,
        "weight": 19.0,
        "sterilized": False,
        "description": "Loyal and playful",
        "birthday": "2019-10-20",
        "birthplace": 20574,
        "sex": 1,
        "coat": 1,
        "bandana_size_id": 1,
        "shirt_size_id": 1,
        "shoe_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
]

dog_owner = [
    {"owner_id": 1, "dog_id": 1},  # Owner 1 has dog Buddy
    {"owner_id": 1, "dog_id": 2},  # Owner 1 has dog Max
    {"owner_id": 1, "dog_id": 3},  # Owner 1 has dog Luna
    {"owner_id": 2, "dog_id": 4},  # Owner 2 has dog Charlie (part of a couple)
    {"owner_id": 3, "dog_id": 4},  # Owner 3 has dog Charlie
    {"owner_id": 4, "dog_id": 5},  # Owner 4 has dog Lucy
    {"owner_id": 5, "dog_id": 5},  # Owner 5 has dog Lucy
    {"owner_id": 6, "dog_id": 6},  # Owner 6 has dog Cooper
    {"owner_id": 7, "dog_id": 7},  # Owner 6 has dog Molly
    {"owner_id": 8, "dog_id": 8},  # Owner 6 has dog Bailey
]


city = pd.read_parquet(f"{parquet_dir}/cities_test.parquet")
state = pd.read_parquet(f"{parquet_dir}/states_test.parquet")
country = pd.read_parquet(f"{parquet_dir}/countries_test.parquet")
# city = pd.read_parquet(f"{parquet_dir}/cities_clean.parquet")
# state = pd.read_parquet(f"{parquet_dir}/states_clean.parquet")
# country = pd.read_parquet(f"{parquet_dir}/countries_clean.parquet")
