import datetime
from dateutil.relativedelta import relativedelta
import pandas as pd
import os
from faker import Faker

# import numpy as np

identification_type = [
    {
        "id": 1,
        "name": "cédula de  ciudadanía",
        "description": "ID for adults",
        "created_at": datetime.datetime.now(),
    },
    {
        "id": 2,
        "name": "tarjeta de identidad",
        "description": "ID for underage",
        "created_at": datetime.datetime.now(),
    },
    {
        "id": 3,
        "name": "NIT",
        "description": "ID for companies",
        "created_at": datetime.datetime.now(),
    },
    {
        "id": 4,
        "name": "Cédula de extranjería",
        "description": "ID for foreigners",
        "created_at": datetime.datetime.now(),
    },
]

status = [
    {
        "id": 1,
        "name": "active",
        "description": "user is currently active in platform",
        "created_at": datetime.datetime.now(),
    },
    {
        "id": 2,
        "name": "inactive",
        "description": "user is currently inactive in platform",
        "created_at": datetime.datetime.now(),
    },
    {
        "id": 3,
        "name": "blocked",
        "description": "user has been blocked",
        "created_at": datetime.datetime.now(),
    },
]

confirmation = [
    {
        "id": 1,
        "name": "false",
        "description": "Account created by another user, identity not confirmed.",
        "created_at": datetime.datetime.now(),
    },
    {
        "id": 2,
        "name": "email",
        "description": "Account confirmed through email.",
        "created_at": datetime.datetime.now(),
    },
    {
        "id": 3,
        "name": "ID",
        "description": "User and pet identity verified through ID document.",
        "created_at": datetime.datetime.now(),
    },
]

size = [
    {"size": "XS"},
    {"size": "S"},
    {"size": "M"},
    {"size": "L"},
    {"size": "XL"},
]

avatar = [
    {
        "name": "clarise",
        "picture": "1.svg",
        "blob_id": 2,
        "description": "generic description",
    },
    {
        "name": "julia",
        "picture": "2.svg",
        "blob_id": 2,
        "description": "generic description",
    },
    {
        "name": "andy",
        "picture": "3.svg",
        "blob_id": 2,
        "description": "generic description",
    },
    {
        "name": "john",
        "picture": "4.svg",
        "blob_id": 2,
        "description": "generic description",
    },
]

sex = [
    {"sex": "macho"},
    {"sex": "hembra"},
]

gender = [
    {"gender": "hombre"},
    {"gender": "mujer"},
    {"gender": "no binario"},
    {"gender": "otro"},
]

blob = [
    {
        "base_url": "https://dantepetclub.blob.core.windows.net/",
        "container": "profilepicture/",
        "token": "?sp=r&st=2024-04-05T01:55:22Z&se=2024-09-11T09:55:22Z&spr=https&sv=2022-11-02&sr=c&sig=ovRTKpszlShJT2HCYUaNKgmBDtdR6T3%2F0%2BhIiiTIXKI%3D",
    },
    {
        "base_url": "https://dantepetclub.blob.core.windows.net/",
        "container": "avatar/",
        "token": "?sp=r&st=2024-04-17T14:39:10Z&se=2025-12-10T22:39:10Z&spr=https&sv=2022-11-02&sr=c&sig=a5xyqAfanZkfWtVGCeK1fmfeAgLZkvVRvwsllUE%2FGbA%3D",
    },
    {
        "base_url": "https://dantepetclub.blob.core.windows.net/",
        "container": "coat/",
        "token": "?sp=r&st=2024-04-17T14:39:52Z&se=2025-09-10T22:39:52Z&spr=https&sv=2022-11-02&sr=c&sig=09ylCMrUq5l%2Fv5Y26yd0uSkRSOK8tSiukYP4F8TfPPY%3D",
    },
]

hobby = [
    {"name": "walking", "icon": "fa-solid fa-paw"},
    {"name": "fetch", "icon": "fa-solid fa-baseball"},
    {"name": "swimming", "icon": "fa-solid fa-person-swimming"},
    {"name": "training", "icon": "fa-solid fa-dumbbell"},
    {"name": "interactive toys", "icon": "fa-solid fa-gamepad"},
    {"name": "pictures", "icon": "fa-solid fa-camera"},
    {"name": "puzzles", "icon": "fa-solid fa-puzzle-piece"},
    {"name": "searching", "icon": "fa-solid fa-magnifying-glass"},
    {"name": "chewing", "icon": "fa-solid fa-bone"},
    {"name": "treats", "icon": "fa-solid fa-cookie-bite"},
    {"name": "socializing with humans", "icon": "fa-solid fa-person"},
    {"name": "socializing with dogs", "icon": "fa-solid fa-dog"},
    {"name": "socializing with cats", "icon": "fa-solid fa-cat"},
    {"name": "socializing with animals", "icon": "fa-solid fa-crow"},
    {"name": "camping", "icon": "fa-solid fa-campground"},
    {"name": "hiking", "icon": "fa-solid fa-person-hiking"},
    {"name": "competitions", "icon": "fa-solid fa-medal"},
    {"name": "beauty contest", "icon": "fa-solid fa-award"},
    {"name": "agility", "icon": "fa-solid fa-stopwatch"},
    {"name": "walks in the park", "icon": "fa-solid fa-tree"},
    {"name": "walks in the city", "icon": "fa-solid fa-tree-city"},
    {"name": "walks in the mall", "icon": "fa-solid fa-store"},
    {"name": "flying", "icon": "fa-solid fa-plane-departure"},
    {"name": "roadtrips", "icon": "fa-solid fa-road"},
    {"name": "hearding", "icon": "fa-solid fa-cow"},
    {"name": "sleeping", "icon": "fa-solid fa-bed"},
    {"name": "barking", "icon": "fa-solid fa-bullhorn"},
    {"name": "howling", "icon": "fa-solid fa-moon"},
    {"name": "eating", "icon": "fa-solid fa-bowl-food"},
    {"name": "Belly Rubs", "icon": "fa-solid fa-hand"},
]

parquet_dir = f"{os.getcwd()}/parquet"

coat = [
    {
        "name": "Black and White",
        "picture": "black.png",
        "thumbnail": "black-tmb.png",
        "blob_id": 3,
        "description": "Classic Border Collie coat color combination of black and white.",
    },
    {
        "name": "Tri-color",
        "picture": "tricolor.png",
        "thumbnail": "tricolor-tmb.png",
        "blob_id": 3,
        "description": "Border Collie coat featuring black, white, and tan markings.",
    },
    {
        "name": "Blue Merle",
        "picture": "blue-merle.png",
        "thumbnail": "blue-merle-tmb.png",
        "blob_id": 3,
        "description": "Blue Merle Border Collie coat with mottled gray and black patterns.",
    },
    {
        "name": "Red Merle",
        "picture": "red-merle.png",
        "thumbnail": "red-merle-tmb.png",
        "blob_id": 3,
        "description": "Red Merle Border Collie coat with mottled red and white patterns.",
    },
    {
        "name": "Blue",
        "picture": "blue.png",
        "thumbnail": "blue-tmb.png",
        "blob_id": 3,
        "description": "Border Collie coat with a base of brown or tan with black-tipped hairs.",
    },
    {
        "name": "Chocolate Tricolor",
        "picture": "chocolate-tricolor.png",
        "thumbnail": "chocolate-tricolor-tmb.png",
        "blob_id": 3,
        "description": "Border Collie coat color combination of red and white.",
    },
    {
        "name": "Chocolate",
        "picture": "chocolate.png",
        "thumbnail": "chocolate-tmb.png",
        "blob_id": 3,
        "description": "Chocolate-colored Border Collie coat with deep brown coloration.",
    },
    {
        "name": "Lilac",
        "picture": "lilac.png",
        "thumbnail": "lilac-tmb.png",
        "blob_id": 3,
        "description": "Lilac-colored Border Collie coat with light brownish-gray coloration.",
    },
    {
        "name": "Red Merle Tricolor",
        "picture": "red-merle-tricolor.png",
        "thumbnail": "red-merle-tricolor-tmb.png",
        "blob_id": 3,
        "description": "Border Collie coat with tiger-stripe-like markings in various shades.",
    },
    {
        "name": "Blue Tricolor",
        "picture": "blue-tricolor.png",
        "thumbnail": "blue-tricolor-tmb.png",
        "blob_id": 3,
        "description": "Parti-color Border Collie coat featuring large patches of two or more colors.",
    },
    {
        "name": "Lilac Tricolor",
        "picture": "lilac-tricolor.png",
        "thumbnail": "lilac-tricolor-tmb.png",
        "blob_id": 3,
        "description": "A combination of black, white, and tan markings with a merle pattern overlay.",
    },
    {
        "name": "Blue Merle Tricolor",
        "picture": "blue-merle-tricolor.png",
        "thumbnail": "blue-merle-tricolor-tmb.png",
        "blob_id": 3,
        "description": "Red Border Collie coat with tan or cream markings.",
    },
]

owner = [
    {
        "user_name": "alvarohc777",
        "email": "aherrada@uninorte.edu.com",
        "phone": "3504515971",
        "picture": "vagabond_infinite_japanese.jpg",
        "blob_id": 1,
        "avatar": 1,
        "password_hash": "hash1",
        "password_salt": "salt1",
        "status_id": 1,
        "confirmation_id": 1,
        "first_name": "Álvaro",
        "middle_name": "Andrés",
        "surname": "Herrada",
        "second_surname": "Coronell",
        "nickname": "Rada",
        "identification_type_id": 1,
        "identification": "1140887494",
        "address": "cra 43B # 82 - 204",
        "birthday": "1996-08-28",
        "birthplace": 20574,
        "gender": 1,
        "shirt_size_id": 1,
        "hat_size_id": 1,
        "pants_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "user_name": "aryasmom",
        "email": "aryascrewkilla@gmail.com",
        "phone": "3207349966",
        "picture": "vagabond_infinite_japanese.jpg",
        "blob_id": 1,
        "avatar": 1,
        "password_hash": "hash2",
        "password_salt": "salt2",
        "status_id": 1,
        "confirmation_id": 1,
        "first_name": "Alexandra",
        "middle_name": "Mercedes",
        "surname": "Ramirez",
        "second_surname": "",
        "nickname": "Meche",
        "identification_type_id": 1,
        "identification": "987654321",
        "address": "cra 43B # 82 - 204",
        "birthday": "1985-03-15",
        "birthplace": 20574,
        "gender": 2,
        "shirt_size_id": 1,
        "hat_size_id": 1,
        "pants_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "user_name": "fulanito123",
        "email": "owner3@example.com",
        "phone": "3504515973",
        "picture": "vagabond_infinite_japanese.jpg",
        "blob_id": 1,
        "avatar": 1,
        "password_hash": "hash3",
        "password_salt": "salt3",
        "status_id": 1,
        "confirmation_id": 1,
        "first_name": "Michael",
        "middle_name": "",
        "surname": "Williams",
        "second_surname": "",
        "nickname": "Mikey",
        "identification_type_id": 1,
        "identification": "543216789",
        "address": "cra 43B # 82 - 204",
        "birthday": "1995-07-20",
        "birthplace": 20574,
        "gender": 1,
        "shirt_size_id": 1,
        "hat_size_id": 1,
        "pants_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "user_name": "owner4",
        "email": "owner4@example.com",
        "phone": "3504515974",
        "picture": "vagabond_infinite_japanese.jpg",
        "blob_id": 1,
        "avatar": 1,
        "password_hash": "hash4",
        "password_salt": "salt4",
        "status_id": 1,
        "confirmation_id": 1,
        "first_name": "Emily",
        "middle_name": "",
        "surname": "Brown",
        "second_surname": "",
        "nickname": "Em",
        "identification_type_id": 1,
        "identification": "987555321",
        "address": "cra 43B # 82 - 204",
        "birthday": "1988-12-10",
        "birthplace": 20574,
        "gender": 2,
        "shirt_size_id": 1,
        "hat_size_id": 1,
        "pants_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "user_name": "owner5",
        "email": "owner5@example.com",
        "phone": "3504515975",
        "picture": "vagabond_infinite_japanese.jpg",
        "blob_id": 1,
        "avatar": 1,
        "password_hash": "hash5",
        "password_salt": "salt5",
        "status_id": 1,
        "confirmation_id": 1,
        "first_name": "David",
        "middle_name": "",
        "surname": "Garcia",
        "second_surname": "",
        "nickname": "Dave",
        "identification_type_id": 1,
        "identification": "654441987",
        "address": "cra 43B # 82 - 204",
        "birthday": "1992-05-25",
        "birthplace": 20574,
        "gender": 1,
        "shirt_size_id": 1,
        "hat_size_id": 1,
        "pants_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "user_name": "owner6",
        "email": "owner6@example.com",
        "phone": "3504515976",
        "picture": "vagabond_infinite_japanese.jpg",
        "blob_id": 1,
        "avatar": 1,
        "password_hash": "hash6",
        "password_salt": "salt6",
        "status_id": 1,
        "confirmation_id": 1,
        "first_name": "Emma",
        "middle_name": "",
        "surname": "Martinez",
        "second_surname": "",
        "nickname": "Emmie",
        "identification_type_id": 1,
        "identification": "987124454",
        "address": "cra 43B # 82 - 204",
        "birthday": "1983-09-05",
        "birthplace": 20574,
        "gender": 2,
        "shirt_size_id": 1,
        "hat_size_id": 1,
        "pants_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "user_name": "owner7",
        "email": "owner7@example.com",
        "phone": "3504515977",
        "picture": "vagabond_infinite_japanese.jpg",
        "blob_id": 1,
        "avatar": 1,
        "password_hash": "hash7",
        "password_salt": "salt7",
        "status_id": 1,
        "confirmation_id": 1,
        "first_name": "Daniel",
        "middle_name": "",
        "surname": "Martinez",
        "second_surname": "",
        "nickname": "Danny",
        "identification_type_id": 1,
        "identification": "124446789",
        "address": "cra 43B # 82 - 204",
        "birthday": "1978-11-30",
        "birthplace": 20574,
        "gender": 1,
        "shirt_size_id": 1,
        "hat_size_id": 1,
        "pants_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "user_name": "owner8",
        "email": "owner8@example.com",
        "phone": "3504515978",
        "picture": "vagabond_infinite_japanese.jpg",
        "blob_id": 1,
        "avatar": 1,
        "password_hash": "hash8",
        "password_salt": "salt8",
        "status_id": 1,
        "confirmation_id": 1,
        "first_name": "Olivia",
        "middle_name": "",
        "surname": "Rodriguez",
        "second_surname": "",
        "nickname": "Liv",
        "identification_type_id": 1,
        "identification": "982224321",
        "address": "cra 43B # 82 - 204",
        "birthday": "1991-04-12",
        "birthplace": 20574,
        "gender": 2,
        "shirt_size_id": 1,
        "hat_size_id": 1,
        "pants_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
]

# Dogs
dog = [
    {
        "first_name": "Buddy",
        "middle_name": "",
        "surname": "Doe",
        "second_surname": "Smith",
        "nickname": "Buddy",
        "height": 30.5,
        "weight": 15.0,
        "sterilized": False,
        "description": "Friendly and playful",
        "birthday": "2018-05-15",
        "birthplace": 20574,
        "sex": 1,
        "coat": 1,
        "bandana_size_id": 1,
        "shirt_size_id": 1,
        "shoe_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "first_name": "Max",
        "middle_name": "",
        "surname": "Johnson",
        "second_surname": "",
        "nickname": "Max",
        "height": 40.0,
        "weight": 20.0,
        "sterilized": False,
        "description": "Loyal and energetic",
        "birthday": "2017-08-20",
        "birthplace": 20574,
        "sex": 1,
        "coat": 1,
        "bandana_size_id": 1,
        "shirt_size_id": 1,
        "shoe_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "first_name": "Luna",
        "middle_name": "",
        "surname": "Williams",
        "second_surname": "",
        "nickname": "Luna",
        "height": 35.0,
        "weight": 18.0,
        "sterilized": True,
        "description": "Affectionate and intelligent",
        "birthday": "2019-02-10",
        "birthplace": 20574,
        "sex": 2,
        "coat": 1,
        "bandana_size_id": 1,
        "shirt_size_id": 1,
        "shoe_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "first_name": "Charlie",
        "middle_name": "",
        "surname": "Brown",
        "second_surname": "",
        "nickname": "Charlie",
        "height": 45.0,
        "weight": 25.0,
        "sterilized": False,
        "description": "Energetic and intelligent",
        "birthday": "2016-11-25",
        "birthplace": 20574,
        "sex": 1,
        "coat": 1,
        "bandana_size_id": 1,
        "shirt_size_id": 1,
        "shoe_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "first_name": "Lucy",
        "middle_name": "",
        "surname": "Garcia",
        "second_surname": "",
        "nickname": "Lucy",
        "height": 32.0,
        "weight": 17.0,
        "sterilized": True,
        "description": "Playful and affectionate",
        "birthday": "2020-04-05",
        "birthplace": 20574,
        "sex": 2,
        "coat": 1,
        "bandana_size_id": 1,
        "shirt_size_id": 1,
        "shoe_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "first_name": "Cooper",
        "middle_name": "",
        "surname": "Martinez",
        "second_surname": "",
        "nickname": "Coop",
        "height": 38.0,
        "weight": 21.0,
        "sterilized": False,
        "description": "Friendly and obedient",
        "birthday": "2018-09-15",
        "birthplace": 20574,
        "sex": 1,
        "coat": 1,
        "bandana_size_id": 1,
        "shirt_size_id": 1,
        "shoe_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "first_name": "Molly",
        "middle_name": "",
        "surname": "Martinez",
        "second_surname": "",
        "nickname": "Molly",
        "height": 42.0,
        "weight": 23.0,
        "sterilized": True,
        "description": "Playful and intelligent",
        "birthday": "2017-06-30",
        "birthplace": 20574,
        "sex": 2,
        "coat": 1,
        "bandana_size_id": 1,
        "shirt_size_id": 1,
        "shoe_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
    {
        "first_name": "Bailey",
        "middle_name": "",
        "surname": "Rodriguez",
        "second_surname": "",
        "nickname": "Bails",
        "height": 37.0,
        "weight": 19.0,
        "sterilized": False,
        "description": "Loyal and playful",
        "birthday": "2019-10-20",
        "birthplace": 20574,
        "sex": 1,
        "coat": 1,
        "bandana_size_id": 1,
        "shirt_size_id": 1,
        "shoe_size_id": 1,
        "created_by": 1,
        "created_at": datetime.datetime.now(),
        "updated_by": 1,
        "updated_at": datetime.datetime.now(),
    },
]

dog_owner = [
    {"owner_id": 1, "dog_id": 1},  # Owner 1 has dog Buddy
    {"owner_id": 1, "dog_id": 2},  # Owner 1 has dog Max
    {"owner_id": 1, "dog_id": 3},  # Owner 1 has dog Luna
    {"owner_id": 2, "dog_id": 4},  # Owner 2 has dog Charlie (part of a couple)
    {"owner_id": 3, "dog_id": 4},  # Owner 3 has dog Charlie
    {"owner_id": 4, "dog_id": 5},  # Owner 4 has dog Lucy
    {"owner_id": 5, "dog_id": 5},  # Owner 5 has dog Lucy
    {"owner_id": 6, "dog_id": 6},  # Owner 6 has dog Cooper
    {"owner_id": 7, "dog_id": 7},  # Owner 6 has dog Molly
    {"owner_id": 8, "dog_id": 8},  # Owner 6 has dog Bailey
]


city = pd.read_parquet(f"{parquet_dir}/cities_test.parquet")
state = pd.read_parquet(f"{parquet_dir}/states_test.parquet")
country = pd.read_parquet(f"{parquet_dir}/countries_test.parquet")
# city = pd.read_parquet(f"{parquet_dir}/cities_clean.parquet")
# state = pd.read_parquet(f"{parquet_dir}/states_clean.parquet")
# country = pd.read_parquet(f"{parquet_dir}/countries_clean.parquet")
